Repository KJLBK/danum-next, pull requests merged in 2024-11, with the labels that each got.

#131 동네게시판 댓글 기능 구현
  src/app/questions/[questionId]/edit/page.jsx
  src/app/questions/[questionId]/page.jsx
  src/app/questions/new/page.jsx
  src/app/questions/page.jsx
  src/app/test/page.jsx
  src/app/villages/[villageId]/edit/page.jsx
  src/app/villages/[villageId]/page.jsx
  src/app/villages/new/page.jsx
  src/app/villages/page.jsx
  src/components/board/new/CommentNew.jsx
  src/components/board/new/CommentNew.module.css
  src/components/board/new/QuillEditor.jsx
  src/components/board/view/BoardItem.jsx
  src/components/board/view/BoardItem.module.css
  src/components/board/view/CommentItem.jsx
  src/components/board/view/CommentItem.module.css
  src/components/board/view/PostInfoPanel.jsx
  src/components/board/view/PostInfoPanel.module.css
  src/components/board/view/QuillViewer.jsx
  src/components/board/view/QuillViewer.module.css
  src/components/question/new/QuestionCommentNew.jsx
  src/hooks/commentSelect.js
  src/services/villageService.js
Labels: feat

#133 게시글 좋아요 기능
  src/components/board/buttons/LikeButton.jsx
  src/components/board/buttons/LikeButton.module.css
  src/components/board/view/PostInfoPanel.jsx
  src/services/questionService.js
  src/services/villageService.js
Labels: feat

#137 chatGPT 추가 질문 기능 구현
  src/app/questions/[questionId]/page.jsx
  src/components/board/view/QuillViewer.jsx
  src/services/chatGPTService.js
Labels: feat

#138 ✨ 메인페이지 기능 구현
  src/app/page.jsx
  src/app/page.module.css
  src/app/questions/page.jsx
  src/app/test/page.jsx
  src/components/common/InfiniteScroll.css
  src/components/common/InfiniteScroll.jsx
  src/components/common/Spinner.css
  src/components/common/Spinner.jsx
  src/components/home/ PopularPosts/Button.jsx
  src/components/home/ PopularPosts/List.jsx
  src/components/home/ PopularPosts/PopularPosts.jsx
  src/components/home/RecentPosts.jsx
  src/hooks/usePopularPosts.js
  src/middleware.js
  src/services/postService.client.js
  src/services/postService.server.js
  src/services/questionService.js
  src/stores/authStore.js
  src/stores/postStore.js
Labels: feat, 영훈

#136 검색 쿼리 파라미터 전달 및 주요 버튼 생성
  src/app/notifications/page.jsx
  src/app/search/page.jsx
  src/app/villages/page.jsx
  src/components/Layout/Header.jsx
  src/components/Layout/Header/NotificationIcon.jsx
  src/components/Layout/Header/NotificationIcon.module.css
  src/components/auth/JoinForm.jsx
  src/components/auth/LoginForm.jsx
  src/components/common/SearchContent.jsx
  src/components/common/SearchContent.module.css
  src/components/common/notificationItem.jsx
  src/components/common/notificationItem.module.css
  src/services/authService.js
  src/services/notificationService.js
Labels: feat

#143 GPT 답변 분리
  src/app/questions/[questionId]/page.jsx
  src/app/questions/[questionId]/page.module.css
Labels: feat

#145 빌드 중 경로 문제 해결
  src/components/Layout/Header.jsx
Labels: fix

#149 authStore 변수명 수정
  src/app/questions/[questionId]/page.jsx
  src/app/villages/[villageId]/page.jsx
  src/app/villages/new/page.jsx
  src/components/board/view/CommentItem.jsx
  src/components/board/view/PostInfoPanel.jsx
Labels: fix

#151 알림창 예외 처리 및 버그 수정
  src/app/notifications/page.jsx
  src/components/Layout/Header.jsx
  src/components/Layout/Header/NotificationsIcon.jsx
Labels: fix

#153 로그인 화면 Intercepting Routes 적용
  src/app/@auth/(.)login/page.jsx
  src/app/@auth/(.)login/page.module.css
  src/app/@auth/default.jsx
  src/app/layout.jsx
  src/components/Layout/Header/LoginButton.jsx
  src/components/auth/LoginForm.jsx
Labels: feat
