Repository KJLBK/danum-next, pull requests merged in 2024-10, with the labels that each got.

#73 채팅기능 서비스 로직
  src/app/chat/[roomId]/page.jsx
  src/app/chat/page.jsx
  src/components/chat/RecentMessagesList.jsx
  src/components/question/QuestionCommentItem.jsx
  src/service/chatService.js
Labels: feat, pull request, 영훈

#79 게시판 관련 페이지 스타일링 구현
  src/app/questions/[questionId]/page.jsx
  src/app/questions/[questionId]/page.module.css
  src/app/questions/page.jsx
  src/app/questions/page.module.css
  src/components/QuillEditor.jsx
  src/components/question/QuestionCommentItem.jsx
  src/components/question/QuestionCommentItem.module.css
  src/components/question/QuestionCommentNew.jsx
  src/components/question/QuestionCommentNew.module.css
  src/components/question/QuestionItem.jsx
  src/components/question/QuestionItem.module.css
Labels: feat, 경빈

#78 CloudFront와 S3 연동을 통한 이미지 URL 사용 및 프로필 사진 로직 추가
  next.config.mjs
  src/app/api/upload/route.js
  src/app/questions/new/page.jsx
  src/components/Layout/Header.jsx
  src/components/auth/GetProfile.jsx
  src/service/authService.js
Labels: feat, 경빈

#82 게시판 삭제 및 수정 기능 구현
  src/app/questions/[questionId]/edit/page.jsx
  src/app/questions/[questionId]/page.jsx
  src/app/questions/[questionId]/page.module.css
  src/components/QuillEditor.jsx
  src/service/questionService.js
Labels: feat, 경빈

#86 게시판 생성 수정 페이지 디자인
  src/app/questions/[questionId]/edit/page.jsx
  src/app/questions/[questionId]/edit/page.module.css
  src/components/QuillEditor.jsx
  src/components/question/QuestionNew.jsx
  src/components/question/QuestionNew.module.css
Labels: feat, 경빈

#88 토큰 가져오는 방식 변경
  src/app/questions/[questionId]/page.jsx
  src/components/question/QuestionNew.jsx
  src/service/chatGPTService.js
  src/service/chatService.js
  src/service/questionService.js
Labels: fix, 경빈

#97 프로필 예외 처리 및 에디터 사진 첨부 방식 수정
  next.config.mjs
  src/app/api/upload/route.js
  src/app/questions/[questionId]/page.jsx
  src/components/Layout/Header.jsx
  src/components/QuillEditor.jsx
  src/components/auth/GetProfile.jsx
  src/components/question/QuestionItem.jsx
  src/components/question/QuestionNew.jsx
  src/services/authService.js
Labels: feat, fix

#99 드롭다운 기능 구현
  src/components/Layout/Header.jsx
  src/components/auth/GetProfile.jsx
  src/components/auth/GetProfile.module.css
Labels: feat, 경빈

#104 프로필이 없을 때 예외 처리
  src/components/auth/GetProfile.jsx
Labels: feat

#112 게시판이 보이지 않는 문제
  src/app/questions/page.jsx
  src/components/question/QuestionItem.jsx
Labels: fix

#110 회원가입 시 주소 값 추가
  src/app/map/page.jsx
  src/components/auth/JoinForm.jsx
Labels: feat

#113 🔨 chore: merge branch '106-chat-state-with-react-query' into 'main'
  src/app/map/page.jsx
  src/app/questions/page.jsx
  src/components/auth/JoinForm.jsx
  src/components/question/QuestionItem.jsx
Labels: fix, 영훈

#118 파일 경로 수정 및 댓글 채택 기능 추가
  src/app/questions/[questionId]/edit/page.jsx
  src/app/questions/[questionId]/page.jsx
  src/app/questions/new/page.jsx
  src/app/questions/page.jsx
  src/components/question/QuestionCommentItem.jsx
  src/components/question/comment/QuestionCommentItem.jsx
  src/components/question/comment/QuestionCommentItem.module.css
  src/components/question/comment/QuestionItem.jsx
  src/components/question/comment/QuestionItem.module.css
  src/components/question/new/QuestionCommentNew.jsx
  src/components/question/new/QuestionCommentNew.module.css
  src/components/question/new/QuestionNew.jsx
  src/components/question/new/QuestionNew.module.css
  src/components/question/new/QuillEditor.jsx
  src/services/questionService.js
Labels: feat, fix

#107 회원가입 폼 개선
  src/app/join/page.jsx
  src/app/map/page.jsx
  src/app/map/page.module.css
  src/components/auth/GetProfile.jsx
  src/components/auth/JoinForm.jsx
  src/components/auth/JoinForm.module.css
  src/components/auth/Profile.jsx
  src/components/auth/Profile.module.css
  src/components/common/Button.jsx
  src/components/common/Button.module.css
  src/components/common/Input.jsx
  src/components/common/Input.module.css
Labels: feat

#121 채택 기능 로직 분리
  src/app/questions/[questionId]/page.jsx
  src/hooks/commentSelect.js
Labels: fix

#123 ✨ 채팅 기능 개선 및 AuthorChatButton 기능 추가
  src/app/test/page.jsx
  src/components/chat/AuthorChatButton.jsx
  src/components/chat/AuthorChatButton.module.css
  src/components/question/view/PostInfoPanel.jsx
  src/hooks/useChatMutations.js
  src/hooks/useChatQueries.js
  src/middleware.js
  src/services/authService.js
  src/services/chatService.js
Labels: feat, fix

#128 게시판 내의 코드 중복 최소화 및 컴포넌트 재사용
  src/app/questions/[questionId]/edit/page.jsx
  src/app/questions/[questionId]/page.jsx
  src/app/questions/new/page.jsx
  src/app/questions/new/page.module.css
  src/app/questions/page.jsx
  src/app/test/page.jsx
  src/app/villages/[villageId]/edit/page.jsx
  src/app/villages/[villageId]/page.jsx
  src/app/villages/new/page.jsx
  src/app/villages/page.jsx
  src/components/common/board/BoardItem.jsx
  src/components/common/board/BoardItem.module.css
  src/components/common/board/PostInfoPanel.jsx
  src/components/common/board/PostInfoPanel.module.css
  src/components/common/board/QuillEditor.jsx
  src/components/common/board/QuillViewer.jsx
  src/components/common/board/QuillViewer.module.css
  src/components/question/comment/QuestionItem.module.css
  src/components/question/new/QuestionNew.jsx
  src/components/village/view/PostInfoPanel.jsx
  src/components/village/view/PostInfoPanel.module.css
  src/components/village/view/VillageItem.jsx
Labels: refactor
